server:
  port: 8999

spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

management:
  endpoint:
    health:
      show-details: always
    env:
      enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: env, health